### ISSUE TITLE
Discuss using Ant Design instead of Bootstrap 4

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/ona-design#14]
We need to decide whether we are going to move forward with Bootstrap or to shift gears and use Ant instead. 

cc @rowo @OluwatobiMayowa @ukanga @mberg @pld

**Comment by ukanga** [comment]
I lean towards Bootstrap because it encourages HTML and CSS over javascript, I think for a UI it is key to stick to principles - https://getbootstrap.com/docs/4.3/extend/approach/. Documentation is clear and precise, quite flexible on how it can be incorporated in a project.

Ant Design seems to rely more on javascript and requiring its own way of structuring the code and functionality. I think that could be limiting and may limit flexibility. I do like that it provides sketch files.

I do recommend we go with Bootstrap.

**Comment by OluwatobiMayowa** [comment]
I quite lean on the side of @ukanga for this. Since this is a fundamental design system, it might be better to go with Bootstrap. Should we then need to go the React route sometime soon, the learnings and experience from this can then be extended to create a Javascript based design system out of Ant.

**Comment by pld** [comment]
Let's stick to Bootstrap.

I agree w/@ukanga it doesn't look like there's a way to use Ant Design as just a design system, it looks like it requires Node and React or React Native, I mean the oob version is Ant Design React. Also proven ecosystem is a big deal, and fact we have other projects based on Bootstrap.

Also agree w/@OluwatobiMayowa that we can run some experiments w/Ant Design, see if it makes sense for our Node and React based projects.
